[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "jwt_auth"
version = "0.1.0"
description = "JWT authentication and validation"
requires-python = ">=3.8"

[tool.maturin]
features = ["pyo3/extension-module"]
