version: '3.8'

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger-agent-observability
    ports:
      # Jaeger UI
      - "16686:16686"
      # Jaeger collector HTTP
      - "14268:14268"
      # Jaeger collector gRPC
      - "14250:14250"
      # Jaeger agent (compact thrift)
      - "6831:6831/udp"
      # Jaeger agent (binary thrift)
      - "6832:6832/udp"
      # Jaeger query HTTP
      - "16687:16687"
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
      - COLLECTOR_OTLP_ENABLED=true
      - LOG_LEVEL=debug
    networks:
      - observability

  # Optional: Prometheus for metrics (future enhancement)
  # prometheus:
  #   image: prom/prometheus:latest
  #   container_name: prometheus-agent-observability
  #   ports:
  #     - "9090:9090"
  #   volumes:
  #     - ./prometheus.yml:/etc/prometheus/prometheus.yml
  #   networks:
  #     - observability

  # Optional: Grafana for visualization (future enhancement)
  # grafana:
  #   image: grafana/grafana:latest
  #   container_name: grafana-agent-observability
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - GF_SECURITY_ADMIN_PASSWORD=admin
  #   networks:
  #     - observability

networks:
  observability:
    driver: bridge
