[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "09-parquet-io"
version = "0.1.0"
description = "PyO3 data science example"
requires-python = ">=3.8"

[tool.maturin]
module-name = "09_parquet_io"
