[package]
name = "property_methods"
version = "0.1.0"
edition = "2021"

[lib]
name = "property_methods"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.22", features = ["extension-module"] }
