[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "property_methods"
version = "0.1.0"
description = "PyO3 example: property_methods"
requires-python = ">=3.8"

[tool.maturin]
features = ["pyo3/extension-module"]
