[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "class_inheritance"
version = "0.1.0"
description = "Class inheritance patterns using composition and traits"
requires-python = ">=3.8"

[tool.maturin]
features = ["pyo3/extension-module"]
