[package]
name = "websocket_basic"
version = "0.1.0"
edition = "2021"

[lib]
name = "websocket_basic"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.22", features = ["extension-module"] }
tokio = { version = "1", features = ["full"] }
