[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "websocket_basic"
version = "0.1.0"
description = "Basic WebSocket handler with PyO3"
requires-python = ">=3.8"

[tool.maturin]
features = ["pyo3/extension-module"]
