[package]
name = "prometheus-metrics"
version = "0.1.0"
edition = "2021"

[dependencies]
pyo3 = { version = "0.20", features = ["auto-initialize"] }
tokio = { version = "1.35", features = ["full"] }
prometheus = { version = "0.13", features = ["process"] }
axum = "0.7"
anyhow = "1.0"
lazy_static = "1.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tower = "0.4"
tower-http = { version = "0.5", features = ["trace"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
rand = "0.8"

[lib]
name = "prometheus_metrics"
path = "src/lib.rs"

[[bin]]
name = "prometheus-metrics"
path = "src/main.rs"
