[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "pandas-groupby"
version = "0.1.0"
description = "Pandas GroupBy and aggregation operations with PyO3"
requires-python = ">=3.8"

[tool.maturin]
module-name = "pandas_groupby"
