[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "ci_cd_example"
version = "0.1.0"
requires-python = ">=3.8"
description = "Example demonstrating CI/CD pipeline for PyO3 packages"
readme = "README.md"
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
]

[tool.maturin]
module-name = "ci_cd_example"
