[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "gil_testing"
version = "0.1.0"
description = "Example 07: GIL release and thread safety testing"
requires-python = ">=3.8"

[tool.maturin]
module-name = "gil_testing"
