[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "parallel-iterators"
version = "0.1.0"
requires-python = ">=3.8"

[tool.maturin]
python-source = "python"
module-name = "parallel_iterators"
