apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  labels:
    app: api-server
immutable: true
data:
  database.host: "postgres.database.svc.cluster.local"
  database.port: "5432"
  database.name: "api_production"

  app.yaml: |
    server:
      port: 8080
      host: 0.0.0.0
      timeout: 30s

    database:
      max_connections: 100
      connection_timeout: 10s

    logging:
      level: info
      format: json

    cache:
      ttl: 3600
      max_size: 1000
