[package]
name = "ab-testing"
version = "0.1.0"
edition = "2021"

[dependencies]
pyo3 = { version = "0.22", features = ["auto-initialize"] }
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rand = "0.8"
statrs = "0.17"
anyhow = "1.0"
chrono = { version = "0.4", features = ["serde"] }

[[bin]]
name = "ab-testing"
path = "src/main.rs"
