[package]
name = "context-management"
version = "0.1.0"
edition = "2021"

[dependencies]
# PyO3 for Python interop
pyo3 = { version = "0.20", features = ["extension-module", "abi3-py38"] }

# Error handling
anyhow = "1.0"
thiserror = "1.0"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Token counting (tiktoken binding)
tiktoken-rs = "0.5"

# Utilities
unicode-segmentation = "1.10"

[lib]
name = "context_manager"
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "context-management"
path = "src/main.rs"
