[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "07-polars-lazy"
version = "0.1.0"
description = "PyO3 data science example"
requires-python = ">=3.8"

[tool.maturin]
module-name = "07_polars_lazy"
