[package]
name = "custom_collection"
version = "0.1.0"
edition = "2021"

[lib]
name = "custom_collection"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.20", features = ["extension-module"] }
