[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "django_model"
version = "0.1.0"
description = "Django model operations optimization"
requires-python = ">=3.8"

[tool.maturin]
features = ["pyo3/extension-module"]
