[package]
name = "model-comparison"
version = "0.1.0"
edition = "2021"

[dependencies]
pyo3 = { version = "0.20", features = ["auto-initialize"] }
tokio = { version = "1.35", features = ["full"] }
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tabled = "0.15"
statrs = "0.17"
chrono = "0.4"

[[bin]]
name = "model-comparison"
path = "src/main.rs"

[lib]
name = "model_comparison"
path = "src/lib.rs"
