[package]
name = "dependencies_example"
version = "0.1.0"
edition = "2021"

[lib]
name = "dependencies_example"
crate-type = ["cdylib"]

[dependencies]
# Core dependency - always required
pyo3 = { version = "0.20", features = ["extension-module"] }

# Rust dependencies used in the extension
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Statistical computations
statrs = "0.16"

[dev-dependencies]
# Only used for testing, not included in wheel
criterion = "0.5"

[features]
# Optional features that can be enabled
advanced = []
