[package]
name = "embedded_simple"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "embedded_simple"
path = "src/main.rs"

[dependencies]
pyo3 = { version = "0.20", features = ["auto-initialize"] }

[profile.release]
opt-level = 3
