[package]
name = "qdrant-integration"
version = "0.1.0"
edition = "2021"
authors = ["PyO3 DSPy RAG Examples"]
description = "Production-ready Qdrant vector database integration with Rust and Python"
license = "MIT"

[dependencies]
# Qdrant client
qdrant-client = "1.10"

# Async runtime
tokio = { version = "1.35", features = ["full"] }

# Error handling
anyhow = "1.0"
thiserror = "1.0"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# HTTP client (for health checks and REST API)
reqwest = { version = "0.11", features = ["json"] }

# Logging
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# UUID generation
uuid = { version = "1.6", features = ["v4", "serde"] }

# Optional: PyO3 for Python bindings
pyo3 = { version = "0.20", features = ["extension-module"], optional = true }

[dev-dependencies]
# Testing utilities
tokio-test = "0.4"
mockito = "1.2"
criterion = "0.5"

[features]
default = []
python = ["pyo3"]

[[bin]]
name = "qdrant-integration"
path = "src/main.rs"

[[bench]]
name = "search_benchmark"
harness = false

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true

[profile.dev]
opt-level = 0
debug = true
