[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "caching_layer"
version = "0.1.0"
description = "Redis/in-memory caching layer"
requires-python = ">=3.8"

[tool.maturin]
features = ["pyo3/extension-module"]
