[package]
name = "type_validation"
version = "0.1.0"
edition = "2021"

[lib]
name = "type_validation"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.22", features = ["extension-module"] }
