[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "property_testing"
version = "0.1.0"
description = "Example 04: Property-based testing with proptest and hypothesis"
requires-python = ">=3.8"

[project.optional-dependencies]
test = ["pytest>=7.0", "hypothesis>=6.0"]

[tool.maturin]
module-name = "property_testing"
