[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "iterator-combinators"
version = "0.1.0"
description = "Iterator combinators (map, filter, chain) with PyO3"
requires-python = ">=3.8"

[tool.maturin]
module-name = "iterator_combinators"
