[package]
name = "flask_middleware"
version = "0.1.0"
edition = "2021"

[lib]
name = "flask_middleware"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.22", features = ["extension-module"] }
