[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "flask_middleware"
version = "0.1.0"
description = "Flask middleware with PyO3"
requires-python = ">=3.8"
dependencies = ["flask>=2.0.0"]

[tool.maturin]
features = ["pyo3/extension-module"]
