[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "complex_types"
version = "0.1.0"
description = "Complex type conversions with Option, Result, nested structures"
requires-python = ">=3.8"

[tool.maturin]
features = ["pyo3/extension-module"]
