[package]
name = "parallel_basic"
version = "0.1.0"
edition = "2021"

[lib]
name = "parallel_basic"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.20", features = ["extension-module"] }
rayon = "1.8"
