apiVersion: v2
name: sample-app
description: A sample Helm chart for Kubernetes deployment
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - web
  - api
home: https://example.com
sources:
  - https://github.com/example/sample-app
maintainers:
  - name: Platform Team
    email: platform@example.com
dependencies: []
