global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'docker-compose'
    environment: 'development'

# Alertmanager configuration (optional)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#           - alertmanager:9093

# Load rules once and periodically evaluate them
# rule_files:
#   - "alerts.yml"

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # DSpy Production Service
  - job_name: 'dspy-production-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['app:8080']
        labels:
          service: 'dspy-production-service'
          environment: 'development'
    scrape_interval: 10s
    scrape_timeout: 5s

  # Redis exporter (if using redis_exporter)
  # - job_name: 'redis'
  #   static_configs:
  #     - targets: ['redis-exporter:9121']
