global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'websocket-service'

scrape_configs:
  - job_name: 'websocket-service'
    static_configs:
      - targets: ['websocket-service:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: '/metrics'
