[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "production-cli"
version = "0.1.0"
requires-python = ">=3.8"

[tool.maturin]
python-source = "python"
module-name = "production_cli"
