[package]
name = "evaluation-framework"
version = "0.1.0"
edition = "2021"

[dependencies]
pyo3 = { version = "0.21", features = ["extension-module", "auto-initialize"] }
tokio = { version = "1.40", features = ["full"] }
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
csv = "1.3"

[lib]
name = "evaluation_framework"
path = "src/lib.rs"

[[bin]]
name = "eval"
path = "src/main.rs"
