[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "error_testing"
version = "0.1.0"
description = "Example 03: Testing error handling and exceptions"
requires-python = ">=3.8"

[project.optional-dependencies]
test = ["pytest>=7.0"]

[tool.maturin]
module-name = "error_testing"
